// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbVmvF5cOwGDkiGb6_n4H3XYUPipZcDrY',
    appId: '1:1000913057108:web:e5da4ad92569f3c46dc4c1',
    messagingSenderId: '1000913057108',
    projectId: 'tradexe-9b85e',
    authDomain: 'tradexe-9b85e.firebaseapp.com',
    storageBucket: 'tradexe-9b85e.firebasestorage.app',
    measurementId: 'G-FXBJST7L0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKfGr7iLhX2UnXjDqDHuft7xOo7YRlS5k',
    appId: '1:1000913057108:android:5608591ffc1a11f46dc4c1',
    messagingSenderId: '1000913057108',
    projectId: 'tradexe-9b85e',
    storageBucket: 'tradexe-9b85e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABhmIV2DitC1WEJWkRmZJcj5sFtsicx_k',
    appId: '1:1000913057108:ios:47077c2e8eb8a0ef6dc4c1',
    messagingSenderId: '1000913057108',
    projectId: 'tradexe-9b85e',
    storageBucket: 'tradexe-9b85e.firebasestorage.app',
    iosBundleId: 'com.example.tradexa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABhmIV2DitC1WEJWkRmZJcj5sFtsicx_k',
    appId: '1:1000913057108:ios:47077c2e8eb8a0ef6dc4c1',
    messagingSenderId: '1000913057108',
    projectId: 'tradexe-9b85e',
    storageBucket: 'tradexe-9b85e.firebasestorage.app',
    iosBundleId: 'com.example.tradexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbVmvF5cOwGDkiGb6_n4H3XYUPipZcDrY',
    appId: '1:1000913057108:web:f0c0effa2229909d6dc4c1',
    messagingSenderId: '1000913057108',
    projectId: 'tradexe-9b85e',
    authDomain: 'tradexe-9b85e.firebaseapp.com',
    storageBucket: 'tradexe-9b85e.firebasestorage.app',
    measurementId: 'G-165B4GQD3J',
  );
}
